
name: .NET

on:
  push:
    branches: 
       -main
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean Dependencies 
      run: dotnet clean
      working-directory: F:\runner\actions-runner\_work\Tic_Tac_Toe\Tic_Tac_Toe

    - name: Restore dependencies
      run: dotnet restore
      working-directory: D:\IIS\TicTacToeRunner\actions-runner\_work\Tic_Tac_Toe\Tic_Tac_Toe

    - name: Build
      run: dotnet build --no-restore
      working-directory: F:\runner\aD:\IIS\TicTacToeRunner\actions-runner\_work\Tic_Tac_Toe\Tic_Tac_Toe

   
